name: StackMob
version: 2.4.6
author: antiPerson/BaconPied
main: uk.antiperson.stackmob.StackMob
website: https://www.spigotmc.org/resources/stackmob.29999/
softdepend: [MythicMobs, MiniaturePets, ProtocolLib, WorldGuard]
description: The only mob-stacking plugin that you will ever need.
api-version: 1.13
load: STARTUP
commands:
    sm:
       description: The main command
permissions:
    stackmob.*:
        description: All administrator commands
    stackmob.kill-all:
        description: Allows for the kill-all method of killing mobs.
    stackmob.kill-step:
        description: Allows for the kill-step method of killing mobs.
    stackmob.kill-step-damage:
        description: Allows for the kill-step-damage method of killing mobs.