name: StackMob
version: 2.2.0
author: antiPerson/BaconPied
main: uk.antiperson.stackmob.StackMob
website: www.spigotmc.org/resources/29999/
softdepend: [MythicMobs, MiniaturePets, ProtocolLib, WorldGuard]
description: The only mob-stacking plugin that you will never need.
load: STARTUP
commands:
    sm:
       description: The main command
permissions:
    stackmob.*:
      description: All administrator commands