name: StackMob
version: 2.2.13
author: antiPerson/BaconPied
main: uk.antiperson.stackmob.StackMob
website: https://www.spigotmc.org/resources/stackmob.29999/
softdepend: [MythicMobs, MiniaturePets, ProtocolLib, WorldGuard]
description: The only mob-stacking plugin that you will ever need.
load: STARTUP
commands:
    sm:
       description: The main command
permissions:
    stackmob.*:
      description: All administrator commands